### ISSUE TITLE
Blob Visual Representation

### ISSUE THREAD

**Issue by Helene-Maxcici** [ipol-journal/ipolDevel#148]
**Demo Title:** Automatic Speech Recognition via Large-Scale Weak Supervision
**Demo ID:** 5555531100005

Our blobs consist of audio files, to which we would like to put a Visual Representation. The first time we tried, it worked, with for example 
![icon1](https://user-images.githubusercontent.com/119662709/217833646-081ee1f5-5f72-47e4-9fd8-96a85bc2de46.png). But when we tried to change to another image e.g. 
![icon2](https://user-images.githubusercontent.com/119662709/217838283-ea4d2503-d0fb-41bd-a787-bd3eefbbe68a.png)
, the visual representation didn't change.

**Comment by hmaciasc** [comment]
Hi, I've changed the VR of "English" blob, could you please reload without cache (command/control + shift + R) next time you need to change a VR to check if that is the problem?

**Comment by mcolom** [comment]
Helene, today we can test this together, along with the other members in your team.

**Comment by mcolom** [comment]
@hmaciasc Thanks for looking at it. Indeed, it seems it's a cache problem.
We change the file, but we keep the exactly the same name for the thumbnail. Google Chrome decides to use its cached copy without any further checks.
Do you think we could add a query string to the URL of the thumbnail of the VR? Something like .../thumb.jpg?random=492348776
