### ISSUE TITLE
3d viewer no more working

### ISSUE THREAD

**Issue by kerautret** [ipol-journal/ipolDevel#167]
Hi all, 
It looks like that the system do not allow to display 3D anymore.
For instance in the published paper that I edit the demo is failing:
https://www.ipol.im/pub/art/2023/418/
![Capture d’écran 2023-04-08 à 09 48 03](https://user-images.githubusercontent.com/772865/230710173-ffa67e5f-e89a-4468-941a-a2cc2759e4a4.png)
It looks like that it is related to the "frame-src-directive" of the content Security Policy.
Perhaps related to the last commits since I tested it not a :one time ago and it was working.
Thanks to all!

**Comment by kerautret** [comment]
perhaps the @mcolom PR #166 fix it ?

**Comment by mcolom** [comment]
Hi Bertrand,

Thanks for reporting!

It stopped working because indeed the security policy is disallowing the use of resources which are external to IPOL. However, given that some demos as yours are loading libraries this way, we'll allow it.

It should work again now :)

**Comment by kerautret** [comment]
Excellent thanks a lot  @mcolom  ;)

**Comment by kerautret** [comment]
I confirm it works perfectly fine !

**Comment by mcolom** [comment]
Great! Thanks for testing too.

**Comment by kerautret** [comment]
@mcolom looks like it is back non visible :(
